# Site settings
title: Nesar Ramachandra
email: your-email@example.com
description: >
  Computational Scientist at Argonne National Laboratory
baseurl: ""
url: "https://nesar.github.io"

# Build settings
markdown: kramdown
future: true

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
